**Questions 1:**
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [ ]:
import numpy as np
arr = np.arange(2,50,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

**Questions 2:**
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [22]:
import numpy as np
def userinput():
  li = list()
  for i in range(5):
    li.append(int(input()))
  return li
li1=list()
li1 = userinput()
li2 =list()
li2 = userinput()
arr1 = np.array(li1)
arr2 = np.array(li2)
arr = np.concatenate((arr1,arr2))
print(arr)
arr =np.sort(arr)
print(arr)


4
5
2
1
0
6
8
7
9
0
[4 5 2 1 0 6 8 7 9 0]
[0 0 1 2 4 5 6 7 8 9]


**Questions 3:**
Write a code snippet to find the dimensions of a ndarray and its size.

In [23]:
import numpy as np
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
print(arr.ndim)
print(arr.size)

2
6


**Questions 4:**
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

Converting of an 1D array to 2D array can be done using two ways
1. using numpy.newaxis()
2. using numpy.expand_dims()


1. Using numpy.newaxis:- The np.newaxis is just an alias for the Python constant None, which means that wherever you use np.newaxis you could also use None:

**How to use:**The np.newaxis is generally used with slicing. It indicates that you want to add an additional dimension to the array. The position of the np.newaxis represents where I want to add dimensions.

In [34]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(arr.shape)
arr1=arr[:, np.newaxis]
print(arr1)
print(arr1.shape)
arr2 = arr[np.newaxis,:]
print(arr2)
print(arr2.shape)

[1 2 3 4 5 6 7]
(7,)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
(7, 1)
[[1 2 3 4 5 6 7]]
(1, 7)


2. Using numpy.expand_dims():- The second method is to use numpy.expand_dims() function that has an intuitive axis kwarg. This function takes two parameters. The first is the array of which you want to increase the dimension of and the second is index/indexes of array on which you want to create a new axis.









In [41]:
import numpy as np
x = np.zeros((3, 4)) 
print(x)
print(x.shape)
y = np.expand_dims(x, axis=1) 
print(y) 
print(y.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)
[[[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]]
(3, 1, 4)


**Questions 5:**
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [44]:
## Horitzontal Stack
import numpy as np
f = np.array([[1,2,3],[4,5,6]])
g = np.array([[7,8,9],[10,11,12]])

print(np.hstack((f, g)))
print(np.vstack((f, g)))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**Questions 6:**
How to get unique items and counts of unique items?

Ans: Python’s numpy library provides a numpy.unique() function to find the unique elements and it’s corresponding frequency in a numpy array.
and returns Sorted unique elements of an array with their corresponding frequency counts NumPy array.

In [46]:
import numpy as np
arr = np.array([1,1,1,1,3,3,2,2,4,5,67,89,900,00,100,100,4])
unique,count =np.unique(arr,return_counts=True)
print('unique elements are ',unique)
print('Counts of the above elements are in the same order',count) 

unique elements are  [  0   1   2   3   4   5  67  89 100 900]
Counts of the above elements are in the same order [1 4 2 2 2 1 1 1 2 1]
